name: "Botaffiumeiro"
version: "1.0.0"
slug: "botaffiumeiro"
description: "Modify Telegram links with affiliate links"
url: "https://github.com/hectorzin/botaffiumeiro/tree/main/ha-addon"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
options:
  bot_token: ""
  delete_messages: true
  excluded_users:
    - id: "HectorziN"
    - id: "danimart1991"
  msg_affiliate_link_modified: "Here is the modified link with our affiliate program:"
  msg_reply_provided_by_user: "Reply provided by"
  amazon_affiliate_id: "botaffiumeiro_cofee-21"
  amazon:
    - domain: amazon.es
      id: "11640"
    - domain: amazon.es
      id: botaffiumeiro_cofee-21
    - domain: amazon.com
      id: hectorzindomo-20
    - domain: amazon.com.au
      id: hectorzindomo-22
    - domain: amazon.co.uk
      hectorzindomo-21
    - domain: amazon.fr
      id: hectorzindo0d-21
    - domain: amazon.it
      id: hectorzindo04-21
    - domain: amazon.de
      id: hectorzindo0e-21
  aliexpress_app_key: ""
  aliexpress_app_secret: ""
  aliexpress_tracking_id: ""
  aliexpress_discount_codes: 
   - line: "ğŸ’¥ CÃ³digos de descuento de AliExpress:"
   - line: "ğŸ’°2$ off for purchases over 20$:ã€IFPTKOHã€‘"
   - line: "ğŸ’°5$ off for purchases over 50$:ã€IFPT35Dã€‘"
   - line: "ğŸ’°25$ off for purchases over 200$:ã€IFPQDMHã€‘"
   - line: "ğŸ’°50$ off for purchases over 400$:ã€IFP5RINã€‘"
  awin_publisher_id: "1639881"
  awin_adversiters:
    - domain: aliexpress.com
      id: "11640"
    - domain: pccomponentes.com
      id: "20982"
    - domain: leroymerlin.es
      id: "20598"
  admitad_publisher_id: "2306205"
  admitad_adversiters:
    - domain: giftmio.com
      id: 93fd4vbk6c873a1e3014d68450d763
  log_level: INFO
schema:
  bot_token: str
  delete_messages: bool?
  excluded_users:
    - id: str?
  msg_affiliate_link_modified: str?
  msg_reply_provided_by_user: str?
  amazon:
    - domain: str?
      id: str?
  aliexpress_app_key: str?
  aliexpress_app_secret: str?
  aliexpress_tracking_id: str?
  aliexpress_discount_codes:
    - line: str?
  awin_publisher_id: str?
  awin_adversiters:
    - domain: str?
      id: str?
  admitad_publisher_id: str?
  admitad_adversiters:
    - domain: str?
      id: str?
  log_level: list(DEBUG|INFO|WARN|ERROR|CRITICAL)

